apiVersion: v1
metadata:
  name: mysql-config
  namespace: {{ .Release.Namespace }}
data:
  my.cnf: |
    [mysqld]
    innodb_default_row_format=dynamic
    character-set-server=utf8mb4
    collation-server=utf8mb4_unicode_ci
    skip-character-set-client-handshake
    default_authentication_plugin=mysql_native_password
    skip-name-resolve
    max_allowed_packet=16M
    log-error=/opt/bitnami/mysql/logs/mysqld.log